import json
import logging
import os
import pandas as pd

CFG_FILE = './backtester.json'
config = {}

#
# Engine's config file.
# We use this for most of the config that we need, to correctly plot the data
# generated by the backtester.
#
ECFG_FILE = '../engine/backtester.json'
econfig = {}

analytics_csvfile = None
cdlsz = None

def load_config():
        global config
        global econfig
        with open(CFG_FILE) as f:
                config = json.load(f)
        with open(ECFG_FILE) as f:
                econfig = json.load(f)

def cdlsz_from_analytics_csv():
        ''' Deduce candle size string from the analytics_csvfile.
        '''
        if analytics_csvfile is None:
                return None

        df_a = pd.read_csv(analytics_csvfile, index_col=0, header=0,
                           parse_dates=True).tz_localize('Asia/Kolkata')
        assert(len(df_a) >= 2)
        td = df_a.index[1] - df_a.index[0]
        if td == pd.Timedelta("1Min"):
                return "1Min"
        elif td == pd.Timedelta("5Min"):
                return "5Min"
        elif td == pd.Timedelta("10Min"):
                return "10Min"
        elif td == pd.Timedelta("15Min"):
                return "15Min"
        elif td == pd.Timedelta("1D"):
                return "1D"
        assert False, "%s has unsupported timedelta (%s)" % (analytics_csvfile, td)


# Load the json config.
load_config()

#
# Now sanitize various config and set easy-access variable names for each
# config setting.
#

#
# Top level data directory containing historical stock data and other useful
# stuff. It has the following structure:
# NSE/
# NSE/{NIFTY_50.csv,NIFTY_AUTO.csv,...}
# NSE/historical/
# NSE/historical/{HDFC,INFY,...}/
# NSE/historical/HDFC/{HDFC_2017.csv,HDFC_2018.csv,...}
# NSE/historical/HDFC/{HDFC.final.5Min.csv,HDFC.final.15Min.csv,...}
#
# NIFTY_50.csv, NIFTY_AUTO.csv is a list of corresponding stocks. The
# historical stock prices are contained in the corresponding directory inside
# NSE/historical/.
#
tld = econfig['tld']
assert(tld != "")
assert(os.path.isdir(tld))

#
# analytics.csv file for additional analytics columns.
#
if 'analytics_outdir' in econfig:
        analytics_outdir = econfig['analytics_outdir']
        analytics_csvfile = None
        if os.path.isdir(analytics_outdir):
                analytics_csvfile = analytics_outdir + "/analytics.csv"
                if not os.path.isfile(analytics_csvfile):
                        analytics_csvfile = None

#
# Stock and candle size to plot.
# We will plot the following candlestick data, along with the other requested
# overlay charts.
# <tld>/NSE/historical/<symbol>/<symbol>.final.<cdlsz>.csv
#
symbol = econfig['analyze_stock']
assert(symbol != "")

#
# Try to deduce candle size from analytics csv file if present, else depend on
# the value provided by the user.
#
cdlsz = cdlsz_from_analytics_csv()
if cdlsz is None and 'cdlsz' in config:
        cdlsz = config['cdlsz']
assert(cdlsz is not None)
assert(cdlsz in ["1Min", "5Min", "10Min", "15Min", "1D"])

# CSV file.
csvfile = tld + "/NSE/historical/" + symbol + "/" + symbol + ".final." + cdlsz + ".csv"
assert(os.path.isfile(csvfile))

#
# CSV file for the 1D dataframe.
# Latter code can check "csvfile_1D is not None" to find out if it needs to
# load 1D dataframe or not.
# We don't need to load 1D dataframe if the cdlsz is already 1D.
#
csvfile_1D = None
if cdlsz != '1D':
        csvfile_1D = tld + "/NSE/historical/" + symbol + "/" + symbol + ".final.1D.csv"
        assert(os.path.isfile(csvfile_1D))

#
# Plots may vary with strategy selection as different strategies may need
# different plots.
#
strategy_selection = econfig["strategy"]["selection"]
strategy = econfig["strategy"][strategy_selection]

starttick = econfig["starttick"]
endtick = econfig["endtick"]
